In [1]:
!pip install pandas numpy matplotlib

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.2-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\prasunethon\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\prasunethon\.venv\Lib\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\prasunethon\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.0 MB 675.6 kB/s eta 0:00:14
   -- ------------------------------------- 0.5/10.0 MB 675.6 kB/s eta 0:00:14
   -- ------------------------------------- 0.5/10.0 MB 675.6 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/10.0 MB 539.5 kB/s eta 0:00:17
   ---- ----------------------------------- 1.0/10.0 MB 655.2 kB/s eta 0:00:14
   ---- ----------------------------------- 1.0/10.0 MB 655.2 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/10.0 MB 623.0 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/10.0 MB 623.0 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/10.0 MB 673.6 kB/s eta 0:00:13
   ------ --------------------------------- 1.6/10.0 MB 673.6 kB/s eta 0:00:13
   -------- ------------------------------- 2.1/10.0 MB 731.7 kB/s eta 0:00:11
   -------- ------------------------------- 2.1/10.0 MB 731.7 kB/s eta 0:00:11
   -------- ------------------------------- 2.1/10.0 MB 731.7 kB/s eta 0:00:11
   --------- ------------------------------ 2.4/10.0 MB 664.4 kB/s eta 0:00:12
   ---------- ----------------------------- 2.6/10.0 MB 702.6 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/10.0 MB 702.6 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/10.0 MB 702.6 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/10.0 MB 702.6 kB/s eta 0:00:11
   ------------ --------------------------- 3.1/10.0 MB 715.7 kB/s eta 0:00:10
   ------------- -------------------------- 3.4/10.0 MB 738.7 kB/s eta 0:00:09
   ------------- -------------------------- 3.4/10.0 MB 738.7 kB/s eta 0:00:09
   -------------- ------------------------- 3.7/10.0 MB 707.9 kB/s eta 0:00:09
   -------------- ------------------------- 3.7/10.0 MB 707.9 kB/s eta 0:00:09
   -------------- ------------------------- 3.7/10.0 MB 707.9 kB/s eta 0:00:09
   --------------- ------------------------ 3.9/10.0 MB 678.4 kB/s eta 0:00:09
   --------------- ------------------------ 3.9/10.0 MB 678.4 kB/s eta 0:00:09
   ---------------- ----------------------- 4.2/10.0 MB 671.6 kB/s eta 0:00:09
   ---------------- ----------------------- 4.2/10.0 MB 671.6 kB/s eta 0:00:09
   ----------------- ---------------------- 4.5/10.0 MB 677.9 kB/s eta 0:00:09
   ----------------- ---------------------- 4.5/10.0 MB 677.9 kB/s eta 0:00:09
   ----------------- ---------------------- 4.5/10.0 MB 677.9 kB/s eta 0:00:09
   ----------------- ---------------------- 4.5/10.0 MB 677.9 kB/s eta 0:00:09
   -------------------- ------------------- 5.0/10.0 MB 669.1 kB/s eta 0:00:08
   -------------------- ------------------- 5.0/10.0 MB 669.1 kB/s eta 0:00:08
   -------------------- ------------------- 5.0/10.0 MB 669.1 kB/s eta 0:00:08
   -------------------- ------------------- 5.0/10.0 MB 669.1 kB/s eta 0:00:08
   -------------------- ------------------- 5.0/10.0 MB 669.1 kB/s eta 0:00:08
   --------------------- ------------------ 5.2/10.0 MB 610.1 kB/s eta 0:00:08
   --------------------- ------------------ 5.2/10.0 MB 610.1 kB/s eta 0:00:08
   --------------------- ------------------ 5.2/10.0 MB 610.1 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/10.0 MB 598.1 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/10.0 MB 598.1 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/10.0 MB 598.1 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/10.0 MB 598.1 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/10.0 MB 574.9 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/10.0 MB 574.9 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/10.0 MB 578.1 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/10.0 MB 578.1 kB/s eta 0:00:07
   ------------------------- -------------- 6.3/10.0 MB 582.2 kB/s eta 0:00:07
   ------------------------- -------------- 6.3/10.0 MB 582.2 kB/s eta 0:00:07
   -------------------------- ------------- 6.6/10.0 MB 582.9 kB/s eta 0:00:06
   -------------------------- ------------- 6.6/10.0 MB 582.9 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/10.0 MB 583.8 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/10.0 MB 583.8 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/10.0 MB 583.8 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/10.0 MB 583.8 kB/s eta 0:00:06
   ---------------------------- ----------- 7.1/10.0 MB 564.5 kB/s eta 0:00:06
   ----------------------------- ---------- 7.3/10.0 MB 577.0 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/10.0 MB 577.0 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/10.0 MB 577.0 kB/s eta 0:00:05
   ------------------------------ --------- 7.6/10.0 MB 566.5 kB/s eta 0:00:05
   ------------------------------- -------- 7.9/10.0 MB 578.5 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/10.0 MB 578.5 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/10.0 MB 578.5 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/10.0 MB 569.5 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/10.0 MB 569.5 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/10.0 MB 575.1 kB/s eta 0:00:03
   --------------------------------- ------ 8.4/10.0 MB 575.1 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/10.0 MB 571.2 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/10.0 MB 571.2 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/10.0 MB 571.2 kB/s eta 0:00:03
   ----------------------------------- ---- 8.9/10.0 MB 570.2 kB/s eta 0:00:02
   ----------------------------------- ---- 8.9/10.0 MB 570.2 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------ --- 9.2/10.0 MB 569.1 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 503.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 503.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 503.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 503.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 503.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 503.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 503.5 kB/s eta 0:00:02
   -------------------------------------- - 9.7/10.0 MB 481.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 481.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 481.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 481.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 481.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 481.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 481.3 kB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 457.8 kB/s  0:00:23
Downloading numpy-2.5.2-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 288.7 kB/s eta 0:00:42
   - -------------------------------------- 0.5/12.6 MB 288.7 kB/s eta 0:00:42
   - -------------------------------------- 0.5/12.6 MB 288.7 kB/s eta 0:00:42
   - -------------------------------------- 0.5/12.6 MB 288.7 kB/s eta 0:00:42
   - -------------------------------------- 0.5/12.6 MB 288.7 kB/s eta 0:00:42
   -- ------------------------------------- 0.8/12.6 MB 272.4 kB/s eta 0:00:44
   -- ------------------------------------- 0.8/12.6 MB 272.4 kB/s eta 0:00:44
   -- ------------------------------------- 0.8/12.6 MB 272.4 kB/s eta 0:00:44
   -- ------------------------------------- 0.8/12.6 MB 272.4 kB/s eta 0:00:44
   -- ------------------------------------- 0.8/12.6 MB 272.4 kB/s eta 0:00:44
   --- ------------------------------------ 1.0/12.6 MB 263.2 kB/s eta 0:00:44
   --- ------------------------------------ 1.0/12.6 MB 263.2 kB/s eta 0:00:44
   --- ------------------------------------ 1.0/12.6 MB 263.2 kB/s eta 0:00:44
   --- ------------------------------------ 1.0/12.6 MB 263.2 kB/s eta 0:00:44
   ---- ----------------------------------- 1.3/12.6 MB 272.8 kB/s eta 0:00:42
   ---- ----------------------------------- 1.3/12.6 MB 272.8 kB/s eta 0:00:42
   ---- ----------------------------------- 1.6/12.6 MB 309.7 kB/s eta 0:00:36
   ---- ----------------------------------- 1.6/12.6 MB 309.7 kB/s eta 0:00:36
   ---- ----------------------------------- 1.6/12.6 MB 309.7 kB/s eta 0:00:36
   ---- ----------------------------------- 1.6/12.6 MB 309.7 kB/s eta 0:00:36
   ----- ---------------------------------- 1.8/12.6 MB 310.3 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.6 MB 310.3 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.6 MB 310.3 kB/s eta 0:00:35
   ----- ---------------------------------- 1.8/12.6 MB 310.3 kB/s eta 0:00:35
   ------ --------------------------------- 2.1/12.6 MB 315.5 kB/s eta 0:00:34
   ------ --------------------------------- 2.1/12.6 MB 315.5 kB/s eta 0:00:34
   ------ --------------------------------- 2.1/12.6 MB 315.5 kB/s eta 0:00:34
   ------ --------------------------------- 2.1/12.6 MB 315.5 kB/s eta 0:00:34
   ------ --------------------------------- 2.1/12.6 MB 315.5 kB/s eta 0:00:34
   ------- -------------------------------- 2.4/12.6 MB 302.6 kB/s eta 0:00:34
   ------- -------------------------------- 2.4/12.6 MB 302.6 kB/s eta 0:00:34
   ------- -------------------------------- 2.4/12.6 MB 302.6 kB/s eta 0:00:34
   ------- -------------------------------- 2.4/12.6 MB 302.6 kB/s eta 0:00:34
   -------- ------------------------------- 2.6/12.6 MB 305.3 kB/s eta 0:00:33
   -------- ------------------------------- 2.6/12.6 MB 305.3 kB/s eta 0:00:33
   -------- ------------------------------- 2.6/12.6 MB 305.3 kB/s eta 0:00:33
   -------- ------------------------------- 2.6/12.6 MB 305.3 kB/s eta 0:00:33
   --------- ------------------------------ 2.9/12.6 MB 308.6 kB/s eta 0:00:32
   --------- ------------------------------ 2.9/12.6 MB 308.6 kB/s eta 0:00:32
   --------- ------------------------------ 3.1/12.6 MB 321.0 kB/s eta 0:00:30
   --------- ------------------------------ 3.1/12.6 MB 321.0 kB/s eta 0:00:30
   --------- ------------------------------ 3.1/12.6 MB 321.0 kB/s eta 0:00:30
   --------- ------------------------------ 3.1/12.6 MB 321.0 kB/s eta 0:00:30
   ---------- ----------------------------- 3.4/12.6 MB 318.3 kB/s eta 0:00:29
   ---------- ----------------------------- 3.4/12.6 MB 318.3 kB/s eta 0:00:29
   ---------- ----------------------------- 3.4/12.6 MB 318.3 kB/s eta 0:00:29
   ----------- ---------------------------- 3.7/12.6 MB 325.6 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.6 MB 325.6 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.6 MB 325.6 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.6 MB 326.9 kB/s eta 0:00:27
   ------------ --------------------------- 3.9/12.6 MB 326.9 kB/s eta 0:00:27
   ------------ --------------------------- 3.9/12.6 MB 326.9 kB/s eta 0:00:27
   ------------ --------------------------- 3.9/12.6 MB 326.9 kB/s eta 0:00:27
   ------------- -------------------------- 4.2/12.6 MB 329.3 kB/s eta 0:00:26
   ------------- -------------------------- 4.2/12.6 MB 329.3 kB/s eta 0:00:26
   -------------- ------------------------- 4.5/12.6 MB 339.4 kB/s eta 0:00:24
   -------------- ------------------------- 4.5/12.6 MB 339.4 kB/s eta 0:00:24
   -------------- ------------------------- 4.5/12.6 MB 339.4 kB/s eta 0:00:24
   -------------- ------------------------- 4.5/12.6 MB 339.4 kB/s eta 0:00:24
   -------------- ------------------------- 4.7/12.6 MB 337.9 kB/s eta 0:00:24
   -------------- ------------------------- 4.7/12.6 MB 337.9 kB/s eta 0:00:24
   --------------- ------------------------ 5.0/12.6 MB 346.5 kB/s eta 0:00:22
   --------------- ------------------------ 5.0/12.6 MB 346.5 kB/s eta 0:00:22
   --------------- ------------------------ 5.0/12.6 MB 346.5 kB/s eta 0:00:22
   --------------- ------------------------ 5.0/12.6 MB 346.5 kB/s eta 0:00:22
   ---------------- ----------------------- 5.2/12.6 MB 342.9 kB/s eta 0:00:22
   ---------------- ----------------------- 5.2/12.6 MB 342.9 kB/s eta 0:00:22
   ---------------- ----------------------- 5.2/12.6 MB 342.9 kB/s eta 0:00:22
   ----------------- ---------------------- 5.5/12.6 MB 348.2 kB/s eta 0:00:21
   ----------------- ---------------------- 5.5/12.6 MB 348.2 kB/s eta 0:00:21
   ------------------ --------------------- 5.8/12.6 MB 354.7 kB/s eta 0:00:20
   ------------------ --------------------- 5.8/12.6 MB 354.7 kB/s eta 0:00:20
   ------------------ --------------------- 5.8/12.6 MB 354.7 kB/s eta 0:00:20
   ------------------- -------------------- 6.0/12.6 MB 354.7 kB/s eta 0:00:19
   ------------------- -------------------- 6.0/12.6 MB 354.7 kB/s eta 0:00:19
   ------------------- -------------------- 6.0/12.6 MB 354.7 kB/s eta 0:00:19
   ------------------- -------------------- 6.0/12.6 MB 354.7 kB/s eta 0:00:19
   ------------------- -------------------- 6.0/12.6 MB 354.7 kB/s eta 0:00:19
   ------------------- -------------------- 6.0/12.6 MB 354.7 kB/s eta 0:00:19
   -------------------- ------------------- 6.6/12.6 MB 362.6 kB/s eta 0:00:17
   -------------------- ------------------- 6.6/12.6 MB 362.6 kB/s eta 0:00:17
   --------------------- ------------------ 6.8/12.6 MB 368.0 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 368.0 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 368.0 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 368.0 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 363.3 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 363.3 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 363.3 kB/s eta 0:00:16
   ----------------------- ---------------- 7.3/12.6 MB 365.7 kB/s eta 0:00:15
   ----------------------- ---------------- 7.3/12.6 MB 365.7 kB/s eta 0:00:15
   ----------------------- ---------------- 7.3/12.6 MB 365.7 kB/s eta 0:00:15
   ----------------------- ---------------- 7.3/12.6 MB 365.7 kB/s eta 0:00:15
   ------------------------ --------------- 7.6/12.6 MB 363.9 kB/s eta 0:00:14
   ------------------------ --------------- 7.6/12.6 MB 363.9 kB/s eta 0:00:14
   ------------------------ --------------- 7.6/12.6 MB 363.9 kB/s eta 0:00:14
   ------------------------ --------------- 7.6/12.6 MB 363.9 kB/s eta 0:00:14
   ------------------------ --------------- 7.9/12.6 MB 363.4 kB/s eta 0:00:14
   ------------------------ --------------- 7.9/12.6 MB 363.4 kB/s eta 0:00:14
   ------------------------ --------------- 7.9/12.6 MB 363.4 kB/s eta 0:00:14
   ------------------------ --------------- 7.9/12.6 MB 363.4 kB/s eta 0:00:14
   ------------------------- -------------- 8.1/12.6 MB 361.5 kB/s eta 0:00:13
   ------------------------- -------------- 8.1/12.6 MB 361.5 kB/s eta 0:00:13
   ------------------------- -------------- 8.1/12.6 MB 361.5 kB/s eta 0:00:13
   -------------------------- ------------- 8.4/12.6 MB 362.7 kB/s eta 0:00:12
   -------------------------- ------------- 8.4/12.6 MB 362.7 kB/s eta 0:00:12
   -------------------------- ------------- 8.4/12.6 MB 362.7 kB/s eta 0:00:12
   --------------------------- ------------ 8.7/12.6 MB 361.8 kB/s eta 0:00:11
   --------------------------- ------------ 8.7/12.6 MB 361.8 kB/s eta 0:00:11
   --------------------------- ------------ 8.7/12.6 MB 361.8 kB/s eta 0:00:11
   --------------------------- ------------ 8.7/12.6 MB 361.8 kB/s eta 0:00:11
   --------------------------- ------------ 8.7/12.6 MB 361.8 kB/s eta 0:00:11
   ---------------------------- ----------- 8.9/12.6 MB 359.6 kB/s eta 0:00:11
   ---------------------------- ----------- 8.9/12.6 MB 359.6 kB/s eta 0:00:11

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv(r"C:\prasunethon\data\raw\del-dtu-cpcb-2024-25.csv")

In [9]:
df.head()

,Station ID,State,City,Station Name,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
0,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:00:00.000000+0000,53.0,248.70,44.87,21.19,66.05,...,NaN,NaN,93.12,0.72,39.64,NaN,0.0,NaN,NaN,NaN
1,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:15:00.000000+0000,51.0,227.17,43.82,19.43,63.25,...,0.54,NaN,93.11,0.70,32.55,NaN,0.0,NaN,NaN,NaN
2,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:30:00.000000+0000,51.0,226.90,44.10,17.78,61.88,...,0.02,NaN,93.14,0.51,26.30,NaN,0.0,NaN,NaN,NaN
3,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:45:00.000000+0000,51.0,226.90,44.24,15.37,59.61,...,NaN,NaN,93.16,0.70,37.58,NaN,0.0,NaN,NaN,NaN
4,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T01:00:00.000000+0000,49.0,226.90,44.86,16.31,61.17,...,NaN,NaN,93.14,0.67,64.41,NaN,0.0,NaN,NaN,NaN

In [10]:
df.shape

(70177, 29)

In [11]:
df.columns.tolist()

['Station ID',
 'State',
 'City',
 'Station Name',
 'Timestamp',
 'PM2.5 (µg/m³)',
 'PM10 (µg/m³)',
 'NO (µg/m³)',
 'NO2 (µg/m³)',
 'NOx (ppb)',
 'NH3 (µg/m³)',
 'SO2 (µg/m³)',
 'CO (mg/m³)',
 'Ozone (µg/m³)',
 'Benzene (µg/m³)',
 'Toluene (µg/m³)',
 'Xylene (µg/m³)',
 'O Xylene (µg/m³)',
 'Eth-Benzene (µg/m³)',
 'MP-Xylene (µg/m³)',
 'AT (°C)',
 'RH (%)',
 'WS (m/s)',
 'WD (deg)',
 'RF (mm)',
 'TOT-RF (mm)',
 'SR (W/mt2)',
 'BP (mmHg)',
 'VWS (m/s)']

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70177 entries, 0 to 70176
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Station ID           70177 non-null  str
 1   State                70176 non-null  str
 2   City                 70176 non-null  str
 3   Station Name         70176 non-null  str
 4   Timestamp            70176 non-null  str
 5   PM2.5 (µg/m³)        65115 non-null  float64
 6   PM10 (µg/m³)         64346 non-null  float64
 7   NO (µg/m³)           67876 non-null  float64
 8   NO2 (µg/m³)          67495 non-null  float64
 9   NOx (ppb)            68232 non-null  float64
 10  NH3 (µg/m³)          67810 non-null  float64
 11  SO2 (µg/m³)          68600 non-null  float64
 12  CO (mg/m³)           68990 non-null  float64
 13  Ozone (µg/m³)        68407 non-null  float64
 14  Benzene (µg/m³)      52445 non-null  float64
 15  Toluene (µg/m³)      0 non-null      float64
 16  Xylene (µg/m³)       0 non-null      float64
 17  O Xylene (µg/m³)     0 non-null      float64
 18  Eth-Benzene (µg/m³)  42195 non-null  float64
 19  MP-Xylene (µg/m³)    46409 non-null  float64
 20  AT (°C)              0 non-null      float64
 21  RH (%)               66542 non-null  float64
 22  WS (m/s)             40743 non-null  float64
 23  WD (deg)             65457 non-null  float64
 24  RF (mm)              60930 non-null  float64
 25  TOT-RF (mm)          70176 non-null  float64
 26  SR (W/mt2)           29336 non-null  float64
 27  BP (mmHg)            1233 non-null   float64
 28  VWS (m/s)            0 non-null      float64
dtypes: float64(24), str(5)
memory usage: 15.5 MB

In [13]:
df.isnull().sum()

Station ID                 0
State                      1
City                       1
Station Name               1
Timestamp                  1
PM2.5 (µg/m³)           5062
PM10 (µg/m³)            5831
NO (µg/m³)              2301
NO2 (µg/m³)             2682
NOx (ppb)               1945
NH3 (µg/m³)             2367
SO2 (µg/m³)             1577
CO (mg/m³)              1187
Ozone (µg/m³)           1770
Benzene (µg/m³)        17732
Toluene (µg/m³)        70177
Xylene (µg/m³)         70177
O Xylene (µg/m³)       70177
Eth-Benzene (µg/m³)    27982
MP-Xylene (µg/m³)      23768
AT (°C)                70177
RH (%)                  3635
WS (m/s)               29434
WD (deg)                4720
RF (mm)                 9247
TOT-RF (mm)                1
SR (W/mt2)             40841
BP (mmHg)              68944
VWS (m/s)              70177
dtype: int64

In [ ]:
missing_percentage = (
    df.isnull().sum() / len(df) * 100
)

missing_percentage.sort_values(
    ascending=False
)

In [14]:
missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().sum() / len(df)) * 100
})

missing_summary = missing_summary.sort_values(
    "missing_percentage",
    ascending=False
)

missing_summary

                     missing_count  missing_percentage
VWS (m/s)                    70177          100.000000
O Xylene (µg/m³)             70177          100.000000
AT (°C)                      70177          100.000000
Toluene (µg/m³)              70177          100.000000
Xylene (µg/m³)               70177          100.000000
BP (mmHg)                    68944           98.243014
SR (W/mt2)                   40841           58.197130
WS (m/s)                     29434           41.942517
Eth-Benzene (µg/m³)          27982           39.873463
MP-Xylene (µg/m³)            23768           33.868646
Benzene (µg/m³)              17732           25.267538
RF (mm)                       9247           13.176682
PM10 (µg/m³)                  5831            8.308990
PM2.5 (µg/m³)                 5062            7.213190
WD (deg)                      4720            6.725850
RH (%)                        3635            5.179760
NO2 (µg/m³)                   2682            3.821765
NH3 (µg/m³)                   2367            3.372900
NO (µg/m³)                    2301            3.278852
NOx (ppb)                     1945            2.771563
Ozone (µg/m³)                 1770            2.522194
SO2 (µg/m³)                   1577            2.247175
CO (mg/m³)                    1187            1.691437
State                            1            0.001425
City                             1            0.001425
Timestamp                        1            0.001425
Station Name                     1            0.001425
TOT-RF (mm)                      1            0.001425
Station ID                       0            0.000000

In [15]:
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

Total rows: 70177
Total columns: 29

In [16]:
df["Station Name"].value_counts(dropna=False)

Station Name
DTU, Delhi - CPCB    70176
NaN                      1
Name: count, dtype: int64

In [17]:
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    errors="coerce"
)

print("Invalid timestamps:", df["Timestamp"].isna().sum())
print("Start:", df["Timestamp"].min())
print("End:", df["Timestamp"].max())

Invalid timestamps: 1
Start: 2024-01-01 00:00:00+00:00
End: 2025-12-31 23:45:00+00:00

In [18]:
df.isnull().sum()

Station ID                 0
State                      1
City                       1
Station Name               1
Timestamp                  1
PM2.5 (µg/m³)           5062
PM10 (µg/m³)            5831
NO (µg/m³)              2301
NO2 (µg/m³)             2682
NOx (ppb)               1945
NH3 (µg/m³)             2367
SO2 (µg/m³)             1577
CO (mg/m³)              1187
Ozone (µg/m³)           1770
Benzene (µg/m³)        17732
Toluene (µg/m³)        70177
Xylene (µg/m³)         70177
O Xylene (µg/m³)       70177
Eth-Benzene (µg/m³)    27982
MP-Xylene (µg/m³)      23768
AT (°C)                70177
RH (%)                  3635
WS (m/s)               29434
WD (deg)                4720
RF (mm)                 9247
TOT-RF (mm)                1
SR (W/mt2)             40841
BP (mmHg)              68944
VWS (m/s)              70177
dtype: int64

In [19]:
df[df["Timestamp"].isna()]

,Station ID,State,City,Station Name,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
35136,2025,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.shape

(70177, 29)

In [22]:
clean_df["Timestamp"] = pd.to_datetime(
    clean_df["Timestamp"],
    errors="coerce"
)

NameError: name 'clean_df' is not defined

In [23]:
clean_df = df.copy()

print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))

Rows: 70177
Columns: 29

In [24]:
clean_df["Timestamp"] = pd.to_datetime(
    clean_df["Timestamp"],
    errors="coerce"
)

In [25]:
print(
    "Invalid timestamps:",
    clean_df["Timestamp"].isna().sum()
)

Invalid timestamps: 1

In [26]:
print("Before removing invalid rows:", len(clean_df))

clean_df = clean_df.dropna(
    subset=["Timestamp"]
).copy()

print("After removing invalid rows:", len(clean_df))

Before removing invalid rows: 70177
After removing invalid rows: 70176

In [27]:
clean_df = clean_df.sort_values(
    "Timestamp"
).reset_index(drop=True)

In [28]:
print(
    "Duplicate rows:",
    clean_df.duplicated().sum()
)

Duplicate rows: 0

In [29]:
missing_summary = pd.DataFrame({
    "missing_count": clean_df.isnull().sum(),
    "missing_percentage": (
        clean_df.isnull().sum() /
        len(clean_df) * 100
    )
})

missing_summary = missing_summary.sort_values(
    "missing_percentage",
    ascending=False
)

missing_summary

                     missing_count  missing_percentage
VWS (m/s)                    70176          100.000000
O Xylene (µg/m³)             70176          100.000000
AT (°C)                      70176          100.000000
Toluene (µg/m³)              70176          100.000000
Xylene (µg/m³)               70176          100.000000
BP (mmHg)                    68943           98.242989
SR (W/mt2)                   40840           58.196534
WS (m/s)                     29433           41.941689
Eth-Benzene (µg/m³)          27981           39.872606
MP-Xylene (µg/m³)            23767           33.867704
Benzene (µg/m³)              17731           25.266473
RF (mm)                       9246           13.175445
PM10 (µg/m³)                  5830            8.307684
PM2.5 (µg/m³)                 5061            7.211867
WD (deg)                      4719            6.724521
RH (%)                        3634            5.178409
NO2 (µg/m³)                   2681            3.820394
NH3 (µg/m³)                   2366            3.371523
NO (µg/m³)                    2300            3.277474
NOx (ppb)                     1944            2.770178
Ozone (µg/m³)                 1769            2.520805
SO2 (µg/m³)                   1576            2.245782
CO (mg/m³)                    1186            1.690036
State                            0            0.000000
Station ID                       0            0.000000
Timestamp                        0            0.000000
City                             0            0.000000
Station Name                     0            0.000000
TOT-RF (mm)                      0            0.000000

In [30]:
print(
    "PM2.5 missing:",
    clean_df["PM2.5 (µg/m³)"].isna().sum()
)

print(
    "PM2.5 missing %:",
    clean_df["PM2.5 (µg/m³)"].isna().mean() * 100
)

PM2.5 missing: 5061
PM2.5 missing %: 7.211867305061559

In [31]:
clean_df["PM2.5 (µg/m³)"].describe()

count    65115.000000
mean        74.776619
std         77.496503
min          0.050000
25%         29.000000
50%         53.000000
75%         92.000000
max       1000.000000
Name: PM2.5 (µg/m³), dtype: float64